- name: Install and configure Nginx with SSL and redirect HTTP to HTTPS
  hosts: ubuntu
  become: true

  tasks:
    - name: Update package repositories
      apt:
        update_cache: yes
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    - name: Modify index.html
      copy:
        content: |
          <html>
          <head>
            <title>Hello World</title>
          </head>
          <body>
            <h1>Hello World</h1>
          </body>
          </html>
        dest: /var/www/html/index.html 
    - name: Create SSL directory & change file permission
      file:
        path: /etc/nginx/ssl
        state: directory
        mode: '0700'

    - name: Generate private key
      openssl_privatekey:
        path: /etc/nginx/ssl/server.key
        size: 2048 
    - name: Use private key to generate Certificate Signing Request(CSR)
      openssl_csr:
        path: /etc/nginx/ssl/server.csr
        privatekey_path: /etc/nginx/ssl/server.key
    - name: Use private key and CSR to generate SSL certificate
      openssl_certificate:
        path: /etc/nginx/ssl/server.crt
        privatekey_path: /etc/nginx/ssl/server.key
        csr_path: /etc/nginx/ssl/server.csr
        provider: selfsigned
    - name: Copy Nginx SSL config file
      copy:
        src: ./nginx/ssl.conf
        dest: /etc/nginx/ssl.conf
    - name: Copy default conf file
      copy:
        src: ./nginx/default.conf
        dest: /etc/nginx/conf.d/default.conf
    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
    
   
   



   
